### ISSUE TITLE
Webcam hangs in Chrome in Android

### ISSUE THREAD

**Issue by kushanksriraj** [googlecreativelab/teachablemachine-community#110]
When opening the site (where I have used tmImage library for model) in Chrome browser on Android, there is lag in video stream of the webcam, frame skips are happening. Also, this is slowing down the model prediction speed.

**Comment by irealva** [comment]
Hi @kushanksriraj could you tell us what type of phone you're using? What android model? It might just be you need a slightly more powerful device to get the video and model to run more smoothly.

**Comment by kushanksriraj** [comment]
Hi @irealva the android version is 8.0.1 and it has 2 gigs of ram with a mediatek cpu.
It's a mid-range samrtphone. Yeah, I guess the same...it may need to be more powerful.
When I hid the webcam div on the site, it works fine.
