### ISSUE TITLE
Name of framework

### ISSUE THREAD

**Issue by Zumbalamambo** [googlecreativelab/teachablemachine-community#111]
Which framework has been used to build teachablemachine website?

**Comment by irealva** [comment]
We've used tensorflow.js for the machine learning component, all of our training code is [here](https://github.com/googlecreativelab/teachablemachine-community/tree/master/libraries).

And for the front end we use web components ([LitElement](https://lit-element.polymer-project.org/) and [lit-html](https://lit-html.polymer-project.org/)) and typescript.

Hope that helps.
