### ISSUE TITLE
Android Instructions don't work with exported .tflite file

### ISSUE THREAD

**Issue by riggaroo** [googlecreativelab/teachablemachine-community#116]
Hi there,
I tried to run the basic instructions to train a tflite model on - https://teachablemachine.withgoogle.com/train/image

I managed to input samples and generate a tflite file and download it. However, the instructions listed after downloading don't work. 
https://github.com/googlecreativelab/teachablemachine-community/blob/master/snippets/markdown/image/tflite/android.md

First problem is that the options for the Model now contain more than just `FLOAT` or `QUANTIZED`. 

``` 
 public enum Model {
    FLOAT_MOBILENET,
    QUANTIZED_MOBILENET,
    FLOAT_EFFICIENTNET,
    QUANTIZED_EFFICIENTNET
  }
```
I tried with all different types of models, and tried to download both the Floating Point and Quantized options on https://teachablemachine.withgoogle.com/train/image

Once changing the two variables specified in the instructions, running the app I get the following crash: 

```
2020-06-19 20:10:20.561 23965-24055/org.tensorflow.lite.examples.classification E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.classification, PID: 23965
    java.lang.IllegalArgumentException: Label number 1000 mismatch the shape on axis 1
        at org.tensorflow.lite.support.common.SupportPreconditions.checkArgument(SupportPreconditions.java:104)
        at org.tensorflow.lite.support.label.TensorLabel.<init>(TensorLabel.java:87)
        at org.tensorflow.lite.support.label.TensorLabel.<init>(TensorLabel.java:105)
        at org.tensorflow.lite.examples.classification.tflite.Classifier.recognizeImage(Classifier.java:263)
        at org.tensorflow.lite.examples.classification.ClassifierActivity$1.run(ClassifierActivity.java:95)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

Not sure what I am doing incorrect but it seems like the sample has changed since the instructions were made?

**Comment by HalfdanJ** [comment]
Thanks for flagging this. It does seem indeed that the android example has gotten out of sync. I will try and see if we can get it updated sometime soon. Please keep the thread posted if you find any solutions for it!

In terms of the options above, it would be FLOAT_MOBILENET or QUANTIZED_MOBILENET that should work now.

**Comment by natowi** [comment]
I am also interested in a solution...

**Comment by natowi** [comment]
Ok, I figured it out (@riggaroo):

Teachable machine files (converted_tflite_quantized)

rename labels.txt to labels2.txt 

rename model.tflite to modelquantized.tflite

go to

`examples-master\examples-master\lite\examples\image_classification\android\app\src\main\assets`

paste labels2.txt and modelquantized.tflite

go to

`examples-master\lite\examples\image_classification\android\app\src\main\java\org\tensorflow\lite\examples\classification\tflite`

open ClassifierQuantizedMobileNet.java to edit

in line 55 insert your new model file name

in line 60 insert your new label file name

now you can build your app without problems.

To enable your model, switch to Quantized_MobileNet

---
You should be able to add a new model in Classifier.java
and create a new file based on ClassifierQuantizedMobileNet.java or ClassifierFloatMobileNet.java with proper names and without replacing an existing model.

**Comment by HalfdanJ** [comment]
Thanks a lot @natowi for solving this! We should probably update the [snippet](https://github.com/googlecreativelab/teachablemachine-community/blob/master/snippets/markdown/image/tflite/android.md) with these instructions. Would you be up for modifying the instructions with these directions?

**Comment by HalfdanJ** [comment]
Fixed with natowi's pr
