### ISSUE TITLE
Tflite option not available for pose detection

### ISSUE THREAD

**Issue by Soumi7** [googlecreativelab/teachablemachine-community#117]
# Tflite option not available for pose detection

For image classification there are three options for uploading or downloading model:
- tensorflow
- tflite
- tensorflow.js

However for pose detection, only tensorflow.js model is available. A tensorflow version is needed at least so that model can be converted to tflite.

**Comment by irealva** [comment]
Thanks for your feature request idea. We're going to close this issue for now as we're not actively working on it just yet, but rest assured we've made a note of it.
