### ISSUE TITLE
Getting different results while using same model

### ISSUE THREAD

**Issue by harshit99-cyber** [googlecreativelab/teachablemachine-community#118]
hello i am trying make a project in which i required certain machine learning model so trained one on teachable machine image model  https://teachablemachine.withgoogle.com/models/CayK9S8cm/ but the problem is if i test that model on website i am getting good results but when i download that model on my local machine i am getting different results .this is because of different image prepossessing technique . i cannot reproduce the same accuracy on my local machine using that model  can some help me on that 

can someone tell me what are the image preprocessing step used by teachable machine image model and how can i reproduce same result

**Comment by harshit99-cyber** [comment]
thank u @HalfdanJ  this is exactly what i want ......can you please mention some more techniques that i can use to increase my model accuracy

**Comment by harshit99-cyber** [comment]
i am trying to classify hand written gestures like "tick ,handwritten alphabets "

**Comment by harshit99-cyber** [comment]
![0](https://user-images.githubusercontent.com/63175240/86045929-f603d480-ba69-11ea-8221-329b2226800e.png)
![5](https://user-images.githubusercontent.com/63175240/86045949-fef4a600-ba69-11ea-832a-bc99f731cadb.png)

**Comment by harshit99-cyber** [comment]
some sample dataset

**Comment by HalfdanJ** [comment]
Do you still experience a difference in quality between the Web UI and when you run your code in nodejs?

**Comment by harshit99-cyber** [comment]
still facing same problem

**Comment by harshit99-cyber** [comment]
this is my code

let img = fs.readFileSync("../test/image.png")
    let tfImage=tf.node.decodeImage(img,channels=3)
    const size = Math.min(tfImage.shape[0], tfImage.shape[1]);
    const centerHeight = tfImage.shape[0] / 2;
    const beginHeight = centerHeight - (size / 2);
    const centerWidth = tfImage.shape[1] / 2;
    const beginWidth = centerWidth - (size / 2);
    const cropedImage=tfImage.slice([beginHeight, beginWidth, 0], [size, size, 3]);
    let batchedImage = cropedImage.expandDims(0);
    batchedImage=batchedImage.toFloat().div(tf.scalar(127)).sub(tf.scalar(1));

    console.log(tfImage.shape)





    batchedImage=tf.image.resizeBilinear(batchedImage,[224,224])
    let data=model.predict(tf.reshape(batchedImage,[1,224,224,3])).dataSync()

**Comment by HalfdanJ** [comment]
From a quick look, this line `const cropedImage=tfImage.slice([beginHeight, beginWidth, 0], [size, size, 3]);` I dont think you want to do that. Instead resize the entire image to 224,244 (so go directly to the `resizeBilinear` line more or less).  At training the full image was squeezed into that size, so if you change the scaling I think the prediction accuracy will go do.

**Comment by harshit99-cyber** [comment]
![Capture](https://user-images.githubusercontent.com/63175240/86147741-6157b000-bb17-11ea-9437-9a8a72507e72.PNG)
But in source code that you mentioned ....their is a croping function , that is why i was doing that step

**Comment by harshit99-cyber** [comment]
actually i am getting better results after cropping the image ,

**Comment by HalfdanJ** [comment]
Ooh you are right. In that case your very tall images will create an issue, since its cropping potentially part of your stroke. 

Maybe try and squeeze the images into a square image before inputting them into teachable machine, and then similarily at runtime, rather then cropping. 

I'm going to close this ticket for now, but if you find other issue feel free to reopen
