### ISSUE TITLE
p5.js (ml5) snippet

### ISSUE THREAD

**Issue by shiffman** [googlecreativelab/teachablemachine-community#12]
Hello! I am working on an example for Teachable Machine and p5.js. I made some adjustments to the current snippet in the beta. My suggested code is at the bottom. I've added some comments and also removed the need for DOM elements opting to render the label text to the canvas itself.

<img width="413" alt="Screen Shot 2019-10-22 at 5 27 18 PM" src="https://user-images.githubusercontent.com/191758/67335332-83f9e980-f4f1-11e9-841b-3cc8354fad9f.png">

One small issue is that the video is not mirrored, I am thinking about how to handle this.

Also, I think rather than copy/paste it might make sense for the interface to provide a link to a p5.js web editor template where the user just has to copy in the model URL. At a minimum, something should note that the code will only run with the p5 and ml5 libraries, e.g.:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/p5.js"></script>
<script src="https://unpkg.com/ml5@0.4.1/dist/ml5.min.js"></script>
```

Would you like me to create the template as part of the ml5 web editor account / examples?

(I should note `0.4.1` does not yet exist, but will include a bug fix that makes the example run, see: https://github.com/ml5js/ml5-library/pull/650)

```javascript
// Classifier Variable
let classifier;
// Model URL
let imageModel = 'https://storage.googleapis.com/tm-models/WfgKPytY/model.json';

// Video
let video;

// To store the classification
let label = "";

// Load the model first
function preload() {
  classifier = ml5.imageClassifier(imageModel);
}

function setup() {
  createCanvas(320, 260);
  // Create the video
  video = createCapture(VIDEO);
  video.size(320, 240);
  video.hide();

  // Start classifying
  classifyVideo();
}

function draw() {
  background(0);
  // Draw the video
  image(video, 0, 0);

  // Draw the label
  fill(255);
  textSize(16);
  textAlign(CENTER);
  text(label, width / 2, height - 4);
}

// Get a prediction for the current video frame
function classifyVideo() {
  classifier.classify(video, gotResult);
}

// When we get a result
function gotResult(error, results) {
  // If there is an error
  if (error) {
    console.error(error);
    return;
  }
  // The results are in an array ordered by confidence.
  console.log(results[0]);
  label = results[0].label;
  // Classifiy again!
  classifyVideo();
}
```

cc @joeyklee

**Comment by shiffman** [comment]
@HalfdanJ Here is a proposed snippet for sound classification. Same requirements (ml5 0.4.1+ and p5.js).

<img width="377" alt="Screen Shot 2019-10-23 at 8 12 58 PM" src="https://user-images.githubusercontent.com/191758/67443122-94819100-f5d1-11e9-908d-6c0a6c92ecd6.png">


```javascript
// Global variable to store the classifier
let classifier;

// Label
let label = 'listening...';

// Teachable Machine model URL:
let soundModel = '________';


function preload() {
  // Load the model
  classifier = ml5.soundClassifier(soundModel);
}

function setup() {
  createCanvas(320, 240);
  // Start classifying
  // The sound model will continuously listen to the microphone
  classifier.classify(gotResult);
}

function draw() {
  background(0);
  // Draw the label in the canvas
  fill(255);
  textSize(32);
  textAlign(CENTER, CENTER);
  text(label, width / 2, height / 2);
}


// The model recognizing a sound will trigger this event
function gotResult(error, results) {
  if (error) {
    console.error(error);
    return;
  }
  // The results are in an array ordered by confidence.
  // console.log(results[0]);
  label = results[0].label;
}
```

**Comment by HalfdanJ** [comment]
Awesome, thanks! Ill copy these in. We will soon move it over so the snippets live in this repo. 

And regarding the link to p5.js, I think that would be great! What would that link look like exactly?

**Comment by irealva** [comment]
Closing this since we just merged the PR for this.

**Comment by irealva** [comment]
Solved by: https://github.com/googlecreativelab/teachablemachine-community/pull/21
