### ISSUE TITLE
Labels not updated if edited after training

### ISSUE THREAD

**Issue by ToonTalk** [googlecreativelab/teachablemachine-community#124]
When I trained and then edited the class names the editing had no effect unless I retrained.

**Comment by HalfdanJ** [comment]
Yes, this can seem a bit unintuitive, but it is the expected behavior. The way that tensorflowjs works, the class names can only be modified at training time, so we are limited by that. Changing class name should trigger the retrain button to become active again. Let me know if I'm misunderstanding your bug report.

**Comment by ToonTalk** [comment]
Thanks. Perhaps a warning should pop up if one edits the labels after training.

**Comment by Dave592309** [comment]
Hey everyone - what are you working on with Teachable Machine? Keen to
understand some of the potential applications.

Dave

**Comment by ToonTalk** [comment]
I'm not sure this the right forum to answer Dave's question but I'll try.

Version 1 of the Teachable Machine inspired very similar efforts (e.g. https://machinelearningforkids.co.uk/#!/worksheets, https://www.mblock.cc/doc/en/use-extensions/teachable-machine.html, and my work https://snap.berkeley.edu/snap/snap.html#present:Username=toontalk&ProjectName=follow%20lean). All of these add the ability for non-expert programmers to _use_ their trained model in their projects.

With version 2 one can save your trained model and use it if you know JavaScript or Python. This week I began to explore importing saved Teachable Machine models into Snap! for projects. See https://snap.berkeley.edu/snap/snap.html#present:Username=toontalk&ProjectName=teachable%20machine%20exercise

**Comment by Dave592309** [comment]
Hey Ken - would you be open to chatting about how your embedding it into
Snap?

I've built a few models and want to use it in Bubble Apps. Here's a link to
my calendar: https://calendly.com/david-mcmanus/15min
