### ISSUE TITLE
pose model export to keras

### ISSUE THREAD

**Issue by rstgar** [googlecreativelab/teachablemachine-community#140]
How I can export your cool pose project models into TF keras?

**Comment by irealva** [comment]
Hi! Thanks for writing in. At this time we unfortunately don't have a converter for the tf.js pose model to keras. It's helpful to know that you need/want this though.

**Comment by irealva** [comment]
Thanks again for your feature request idea. We're going to close this issue for now as we're not actively working on it just yet, but rest assured we've made a note of it.
