### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by samarth70** [googlecreativelab/teachablemachine-community#141]
Unable to convert and download model in .p5 file . Shows some problem in converting the file.

**Comment by irealva** [comment]
Hi, could you provide a bit more detail on your issue? Maybe a screenshot? Did this happen for just one model you trained or multiple projects?

**Comment by samarth70** [comment]
It was working fine afterwards. Thank you for the concern.

**Comment by irealva** [comment]
Ok, closing for now.
