### ISSUE TITLE
[BUG]: Model not updating on link sharing 

### ISSUE THREAD

**Issue by tlsaeger** [googlecreativelab/teachablemachine-community#151]
If I upload my model using the link option in the Export Model window, everything works as expected. The class-names show up as I defined them, but if I want to update the class-names for example. I can do so and I can retrain the model and everything looks fine. I can upload the new version, but if I open up the link the changes are not reflected there. Neither in the browser on the direct link nor using it for example in my ml5 project. 

In my example I tried to change the class-name »Nichts« (German for nothing) to BRB. 
As I mentioned it is visible in the editor, but not in the link-preview. 

Running on Chrome v. 86 macOS 10.15.7

Still an awesome platform, thanks for all the hard work!

![editor](https://user-images.githubusercontent.com/33449313/98807454-f601e100-241a-11eb-93f8-6fd03c34214f.png)
![link-preview](https://user-images.githubusercontent.com/33449313/98807451-f4d0b400-241a-11eb-906f-40d9718b3033.png)

**Comment by HalfdanJ** [comment]
When you re-upload a model, it overwrites the same file, and I've experienced that you need to do a hard-reload (clear cache) in order for your computer to download the new model file.

**Comment by tlsaeger** [comment]
That does indeed work, thanks for the workaround!
