### ISSUE TITLE
DOMException on trying to import tensorflow models

### ISSUE THREAD

**Issue by MarkKocherovsky** [googlecreativelab/teachablemachine-community#175]
I'm trying to import my teachable machine js model into a Scratch extension. I'm following directions as given [here](https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/README.md). I've got the following import code in my ``index.js`` file:

```
import * as tf from '@tensorflow/tfjs';
import * as tmImage from '@teachablemachine/image';
```

The code compiles fine. However, when I launch scratch and the extension, the console returns the following error: ``Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8601/PalmReader' failed to load.``

``PalmReader`` is my extension, and ``localhost:8601`` is my local build of scratch. Here is the code where I am actually using the model:

```
importModel() {

        //from https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/README.md
        const url = <My Model>;
        const modelUrl = url + "model.json";
        const metadataUrl = url + "metadata.json";
        model = await tmImage.load(modelUrl, metadataUrl);
        maxPredictions = model.getTotalClasses();
    }
```

``model`` and ``maxPredictions`` are declared elsewhere in the file in global scope.

**Comment by dalelane** [comment]
@MarkKocherovsky I'm not sure why your code isn't working, but if it helps, I've got a fork of Scratch that can load Teachable Machine models at https://machinelearningforkids.co.uk/pretrained which you're welcome to use

**Comment by MarkKocherovsky** [comment]
> @MarkKocherovsky I'm not sure why your code isn't working, but if it helps, I've got a fork of Scratch that can load Teachable Machine models at https://machinelearningforkids.co.uk/pretrained which you're welcome to use

Thank you very much for your offer; I'll check it out, but I'd also like to be able to import tf directly into scratch through an extension. I know it's because I'm using a sandboxed extension, so that's more of a scratch issue, I think.

**Comment by MarkKocherovsky** [comment]
This issue is solved, see here: [https://github.com/LLK/scratch-vm/issues/2914](https://github.com/LLK/scratch-vm/issues/2914)
