### ISSUE TITLE
[BUG]: Title Something went wrong while exporting quantized model of tflite

### ISSUE THREAD

**Issue by CodeBlack-121855** [googlecreativelab/teachablemachine-community#225]
**Describe the bug**
I'm working with android app and for that when I'm exporting tflite model in quantizer version it shows an error "Something went wrong while converting".
 Note : I've created 11 classes with approx. 200 images in each class. 

**Screenshots**
![Screenshot 2021-06-16 083144](https://user-images.githubusercontent.com/76609504/122151832-dc77ba80-ce7d-11eb-8283-8b093bb0fe3a.jpg)

**Desktop :**
 - OS: Windows 10
 - Browser : Chrome
 - Version : Latest 2021 version

**Comment by Arinjay35** [comment]
Iam also getting the same issue. Can we know how to fix this issue. Iam doing this as part of my school project. Please help.

**Comment by leoncoolmoon** [comment]
I also experience this. the file download is a broken zip file. The broken file is actually a "404" file for tflite.zip and "502" for tinyml.zip

**Comment by Soulkrown** [comment]
I also get the same issue. Can you help me with this problem, please?

**Comment by wenxiangjiang** [comment]
I also get the same issue, this situation has been going on for a long time. Can someone fix it please?

**Comment by HalfdanJ** [comment]
Apologies it took so long to get this resolved. Turned out to be a much bigger issue than we had anticipated. We have now rolled out a new version that hopefully should solve this issue. Please re-open if its still giving you issues.

**Comment by wenxiangjiang** [comment]
@HalfdanJ It looks like the issue still exists.

**Comment by HalfdanJ** [comment]
@wenxiangjiang which model conversion is giving you issues, and is it only a specific one or all conversions that fail?

**Comment by wenxiangjiang** [comment]
@HalfdanJ I want to convert `TF Lite Quantized`.

All conversions will fail, but occasionally `Keras` will succeed.

<img width="1673" alt="20210810" src="https://user-images.githubusercontent.com/10527100/128881962-c54c3126-8936-4c23-b690-a921008e3f2d.png">

**Comment by HalfdanJ** [comment]
Interesting. I've been trying to reproduce without any luck, and what surpises me is that I dont see any errors in the quantize converter logs. 

Two followup questions:
- Any chance you could share your project/images? I wonder if there could be a connection to that
- Can you click on the red line in the network inspector in your screeenshot and show me both the headers tab and the response tab

**Comment by wenxiangjiang** [comment]
@HalfdanJ 

Thanks for your response.

I just tried again, although I still get an error, but I will also download a file successfully, but the file cannot be decompressed.

<img width="1678" alt="20210811-085754" src="https://user-images.githubusercontent.com/10527100/128953855-e19cf348-c7ad-4e88-adb4-76d89fe9a3a5.png">

**Comment by HalfdanJ** [comment]
Thanks @wenxiangjiang , i'm now able to identify the issue here as well. I don't have a solution for it yet, but will keep you posted.

**Comment by wenxiangjiang** [comment]
@HalfdanJ Thank you for your continued response, I just tested this issue and it seems to have been resolved.

**Comment by SPEAR22** [comment]
@HalfdanJ Hey i am  getting the same problem what proxy changes should be done so that I can download the quantized model..

**Comment by AbhishekMahadik** [comment]
> @HalfdanJ Hey i am getting the same problem what proxy changes should be done so that I can download the quantized model..

I am also facing the same issue..
