### ISSUE TITLE
Not seeing an option to export as tensorflowlite..?

### ISSUE THREAD

**Issue by MarkBurvs** [googlecreativelab/teachablemachine-community#242]
When clicking export, I'm only seeing an option to export as Tensorflow.js, and there's no option to export as Tensorflow Lite as shown [in the tutorial video](https://www.youtube.com/watch?v=n-zeeRLBgd0)

Has this option been removed? 

<img width="823" alt="Screenshot 2021-08-20 at 12 55 16" src="https://user-images.githubusercontent.com/9461289/130229915-a53d6c06-ac73-4a4f-b414-1190b717a80a.png">

**Comment by HalfdanJ** [comment]
We unfortunately do not support it for pose model. Only for audio and image
