### ISSUE TITLE
[BUG]: tiny_image / Processing 4 - package “javax.xml.bind” does not exist

### ISSUE THREAD

**Issue by andreacatta** [googlecreativelab/teachablemachine-community#246]
**Describe the bug**
TM_Connector.pde doesn't compile.
I was following the tutorial [here](https://github.com/googlecreativelab/teachablemachine-community/blob/master/snippets/markdown/tiny_image/GettingStarted.md). 

**To Reproduce**
1. open Processing IDE 4
2. install ControlP5, Websockets libraries
3. restart application
4. launch TM_Connector.pde

**Relevant Links**
https://github.com/googlecreativelab/teachablemachine-community/tree/master/snippets/markdown/tiny_image/tiny_templates/TMConnector/TM_Connector

**Expected behavior**
compile the sketch 

**Screenshots**
![immagine](https://user-images.githubusercontent.com/6803317/134710542-7d5c0d37-404b-4567-9088-46c40d18be2a.png)

**Desktop (please complete the following information):**
 - OS: same behavior on both macOS BigSur, Windows 10
 - Processing 4.01b

**Comment by joydisette** [comment]
@andreacatta  I ran into the same issue and later realized it comes from processing itself. Their latest version is in beta, and you won't be able to use the script. You should be able to run the file on the version 3.5.4 available on their [Download page. ](https://processing.org/download)

**Comment by andreacatta** [comment]
it works perfectly with 3.5.4 on both Win / Mac (M1 and intel).
thank you @joydisette, you made my day!

**Comment by andreacatta** [comment]
solved by opening the sketch with Processing 3.5.4

**Comment by moisesStevend** [comment]
great, it works for me as well.

By the way, If you don't see the list port. just comment on this part:

`portNames = filteredPorts(portNames);`  // this part makes wrong my code
