### ISSUE TITLE
How to clone official website to local env？

### ISSUE THREAD

**Issue by Triment** [googlecreativelab/teachablemachine-community#284]
The website can't visit by my network with no proxy due to firewall，So I need to make it locally

**Comment by HalfdanJ** [comment]
The site itself is not open source at this time, so its not possible to run the site locally.

**Comment by mikeymckay** [comment]
Unless it is using some kind of external source for API calls, which I don't believe it is, it should be possible. All of the source code is frustratingly obfuscated and the tool just isn't setup to maximize usability (can't upload audio files, for example) but at the end of the day it's all javascript executing locally in your browser. You just have to hack your way through it.

**Comment by winnchen** [comment]
> The site itself is not open source at this time, so its not possible to run the site locally.

I have just found this website: https://train.aimaker.space/train/.
It looks like a copy of the official website, with some modifications such as delete all stuffs about Google Drive.
I am just wondering if the official itself is not open source, how could they build this website so similarly?

<img width="2068" alt="image" src="https://user-images.githubusercontent.com/13064618/204482348-60d2793a-c999-4efa-a595-763784a10af2.png">
