### ISSUE TITLE
How to build the project into your own server?

### ISSUE THREAD

**Issue by zzb16888** [googlecreativelab/teachablemachine-community#302]
How to build the project into your own server?

**Comment by sryu1** [comment]
Hi @zzb16888 What do you mean by build the project? Do you mean the model?

**Comment by zzb16888** [comment]
> > How to build the project into your own server?
> 
> @zzb16888 I guess your is:
> 
> ## Can I use Teachable Machine models with other libraries and platforms?
> > Yes. You can export your model as a TensorFlow.js model and host it on Teachable Machine, so you can call it into any website or app. You can also convert it to TensorFlow and TensorFlow Lite and download it for local use.
> 
> read more
> 
> > Models made with Teachable Machine are TensorFlow.js models, so you can export them and use them anywhere Javascript runs — like on a website, on a server, or in some prototyping apps like Framer. Additionally, you can export your model to some other formats to use them in other platforms and environments.

I mean: https://teachablemachine.withgoogle.com/train The same functions are built on their own web pages.

**Comment by zzb16888** [comment]
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/51110833/197468230-ef65d6cf-2cc6-48f0-bf55-5555ceee0919.png">
That means you can do the same training function as this project on your own website？
Thank you for your warm reply

**Comment by zzb16888** [comment]
Visit your own website, and you can do some of the functions in the above picture

**Comment by sryu1** [comment]
Check out the source code for this repo, that's the code for everything in the site

**Comment by zzb16888** [comment]
> 查看此 repo 的源代码，这是站点中所有内容的代码

Hello, is the source code of this site open source? I want to build it for local use！Thank you very much

**Comment by zzb16888** [comment]
https://github.com/googlecreativelab/teachablemachine-community/issues/284
But when I saw this, it seemed that it could not be built locally

**Comment by sryu1** [comment]
Hmm, It may be due to licensing issues, since there is the code for how it trains the data and all but no source for how the api works...

**Comment by zzb16888** [comment]
> 

Can the source code be set up for use? I will simply use it after setting up
I don't need to understand the principle
