### ISSUE TITLE
How can i create....

### ISSUE THREAD

**Issue by QiaoTuCodes** [googlecreativelab/teachablemachine-community#311]
dear creator:
i want know about how to create teachable machine copy in my local computer machine?
the teachable machine website it's open sources for anyone right?

**Comment by sryu1** [comment]
The code that trains the models are open source, the website itself isn't open source.

**Comment by QiaoTuCodes** [comment]
> 训练模型的代码是开源的，网站本身不是开源的。

oh! got it! thanks!
