### ISSUE TITLE
Prediction are different in tensorflow.js from the web one

### ISSUE THREAD

**Issue by mehdish3022** [googlecreativelab/teachablemachine-community#321]
I've trained a model on multiple classes and it worked very well when I tested it on the web but when I imported my model to a local tensorflowjs the predictions were completely wrong.

**Comment by sryu1** [comment]
I'm guessing it'll be because the js snippet is outdated, if possible, can you just check if it works if you use the keras snippet? You need python though, just to check that the model is fine...

**Comment by mehdish3022** [comment]
It does work with keras tensorflow

**Comment by sryu1** [comment]
Ok, then it's a problem with the tfjs snippet, I'll try looking into it, however, if you find a way to make it work, it'll be appreciated :)

**Comment by mehdish3022** [comment]
I converted the model into a tensorflowjs graph model and it kinda works but the predictions are wrong and sometimes inefficient

**Comment by sryu1** [comment]
It's the problem with the tensorflowjs code snippet, not the model itself, since the keras model is actually originally a tfjs model but converted to keras.

**Comment by mehdish3022** [comment]
so how do

**Comment by mehdish3022** [comment]
How do I solve the problem?

**Comment by mehdish3022** [comment]
How do I solve this problem?

**Comment by sryu1** [comment]
Could you try using the snippet from my repo here?
https://github.com/sryu1/teachablemachine-community/blob/master/snippets/markdown/image/tensorflowjs

**Comment by mehdish3022** [comment]
> Could you try using the snippet from my repo here? https://github.com/sryu1/teachablemachine-community/blob/master/snippets/markdown/image/tensorflowjs

it works now
