### ISSUE TITLE
Repository Collaborator

### ISSUE THREAD

**Issue by sryu1** [googlecreativelab/teachablemachine-community#322]
Hi @HalfdanJ, Since you are very busy nowadays, is it possible if I can be a repo collaborator for this repository so I can manage Issues and pull requests?

**Comment by HalfdanJ** [comment]
Hey @sryu1, i really really appreciate your contributions here lately! I'm unfortunately not able to add collaborators to the repository directly due to how Google manages the organization.

**Comment by sryu1** [comment]
Ah, ok, that's all good then.
