### ISSUE TITLE
[BUG]: docker failed to start

### ISSUE THREAD

**Issue by zzb16888** [googlecreativelab/teachablemachine-community#323]
https://github.com/googlecreativelab/teachablemachine-community/tree/master/snippets/converter

audio_1  | [2023-02-02 12:53:41 +0000] [1] [INFO] Shutting down: Master
audio_1  | [2023-02-02 12:53:41 +0000] [1] [INFO] Reason: Worker failed to boot.
image_1  | [2023-02-02 12:53:41 +0000] [1] [INFO] Shutting down: Master
image_1  | [2023-02-02 12:53:41 +0000] [1] [INFO] Reason: Worker failed to boot.
In the process of docker-compose up -d, E: Version '15.0' for 'edgetpu-compiler' was not found
ERROR: Service 'image' failed to build: The command '/bin/sh -c echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources .list.d/coral-edgetpu.list && apt-get update && apt install edgetpu-compiler=15.0 -y' returned a non-zero code: 100
Starting converter_tiny_1  ... done
Attaching to converter_image_1, converter_tiny_1, converter_audio_1
audio_1  | [2023-02-02 12:29:41 +0000] [1] [INFO] Starting gunicorn 19.9.0
audio_1  | [2023-02-02 12:29:41 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
audio_1  | [2023-02-02 12:29:41 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
audio_1  | [2023-02-02 12:29:41 +0000] [9] [INFO] Booting worker with pid: 9
image_1  | [2023-02-02 12:29:41 +0000] [1] [INFO] Starting gunicorn 19.9.0
image_1  | [2023-02-02 12:29:41 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
image_1  | [2023-02-02 12:29:41 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
tiny_1   | [2023-02-02 12:29:41 +0000] [1] [INFO] Starting gunicorn 20.0.4
tiny_1   | [2023-02-02 12:29:41 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
tiny_1   | [2023-02-02 12:29:41 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
image_1  | [2023-02-02 12:29:41 +0000] [8] [INFO] Booting worker with pid: 8
tiny_1   | [2023-02-02 12:29:41 +0000] [9] [INFO] Booting worker with pid: 9
audio_1  | email-validator not installed, email fields will be treated as str.
audio_1  | To install, run: pip install email-validator
tiny_1   | email-validator not installed, email fields will be treated as str.
tiny_1   | To install, run: pip install email-validator
image_1  | email-validator not installed, email fields will be treated as str.
image_1  | To install, run: pip install email-validator
audio_1  | 2023-02-02 12:29:42.138150: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
audio_1  | 2023-02-02 12:29:42.138313: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
image_1  | 2023-02-02 12:29:42.464667: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
image_1  | 2023-02-02 12:29:42.464726: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
audio_1  | [2023-02-02 12:29:44 +0000] [9] [ERROR] Exception in worker process
audio_1  | Traceback (most recent call last):
audio_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
audio_1  |     worker.init_process()
audio_1  |   File "/usr/local/lib/python3.6/site-packages/uvicorn/workers.py", line 47, in init_process
audio_1  |     super(UvicornWorker, self).init_process()
audio_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
audio_1  |     self.load_wsgi()
audio_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
audio_1  |     self.wsgi = self.app.wsgi()
audio_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
audio_1  |     self.callable = self.load()
audio_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
audio_1  |     return self.load_wsgiapp()
audio_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
audio_1  |     return util.import_app(self.app_uri)
audio_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
audio_1  |     __import__(module)
audio_1  |   File "/app/api.py", line 23, in <module>
audio_1  |     import tensorflow as tf
audio_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/__init__.py", line 41, in <module>
audio_1  |     from tensorflow.python.tools import module_util as _module_util
audio_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 48, in <module>
audio_1  |     from tensorflow.python import keras
audio_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 25, in <module>
audio_1  |     from tensorflow.python.keras import models
audio_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 20, in <module>
audio_1  |     from tensorflow.python.keras import metrics as metrics_module
audio_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/metrics.py", line 37, in <module>
audio_1  |     from tensorflow.python.keras import activations
audio_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 18, in <module>
audio_1  |     from tensorflow.python.keras.layers import advanced_activations
audio_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/layers/__init__.py", line 146, in <module>
audio_1  |     from tensorflow.python.keras.layers.normalization import LayerNormalization
audio_1  | ImportError: cannot import name 'LayerNormalization'
audio_1  | [2023-02-02 12:29:44 +0000] [9] [INFO] Worker exiting (pid: 9)
image_1  | [2023-02-02 12:29:44 +0000] [8] [ERROR] Exception in worker process
image_1  | Traceback (most recent call last):
image_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
image_1  |     worker.init_process()
image_1  |   File "/usr/local/lib/python3.6/site-packages/uvicorn/workers.py", line 47, in init_process
image_1  |     super(UvicornWorker, self).init_process()
image_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
image_1  |     self.load_wsgi()
image_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
image_1  |     self.wsgi = self.app.wsgi()
image_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
image_1  |     self.callable = self.load()
image_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
image_1  |     return self.load_wsgiapp()
image_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
image_1  |     return util.import_app(self.app_uri)
image_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
image_1  |     __import__(module)
image_1  |   File "/app/api.py", line 22, in <module>
image_1  |     import tensorflow as tf
image_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/__init__.py", line 41, in <module>
image_1  |     from tensorflow.python.tools import module_util as _module_util
image_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 47, in <module>
image_1  |     from tensorflow.python import keras
image_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 27, in <module>
image_1  |     from tensorflow.python.keras import models
image_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/models.py", line 27, in <module>
image_1  |     from tensorflow.python.keras.engine import sequential
image_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py", line 27, in <module>
image_1  |     from tensorflow.python.keras import layers as layer_module
image_1  |   File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/layers/__init__.py", line 174, in <module>
image_1  |     from tensorflow.python.keras.layers.normalization import LayerNormalization
image_1  | ImportError: cannot import name 'LayerNormalization'
image_1  | [2023-02-02 12:29:44 +0000] [8] [INFO] Worker exiting (pid: 8)
audio_1  | [2023-02-02 12:29:44 +0000] [1] [INFO] Shutting down: Master
audio_1  | [2023-02-02 12:29:44 +0000] [1] [INFO] Reason: Worker failed to boot.
converter_audio_1 exited with code 3
tiny_1   | [2023-02-02 12:29:45 +0000] [9] [INFO] Started server process [9]
tiny_1   | [2023-02-02 12:29:45 +0000] [9] [INFO] Waiting for application startup.
image_1  | [2023-02-02 12:29:45 +0000] [1] [INFO] Shutting down: Master
image_1  | [2023-02-02 12:29:45 +0000] [1] [INFO] Reason: Worker failed to boot.
converter_image_1 exited with code 3
tiny_1   | [2023-02-02 12:30:16 +0000] [9] [INFO] ('54.249.205.93', 24149) - "GET / HTTP/1.1" 404

**Comment by sryu1** [comment]
Hey, what did you try doing? And where did that error come up?

**Comment by sryu1** [comment]
Ooh, I didn't read the title... Sorry

**Comment by sryu1** [comment]
Was that what happened when you `docker compose up`?

**Comment by zzb16888** [comment]
Yes, it's solved, it's a version problem, the latest version of the group is fine
