### ISSUE TITLE
Uploading zip file with audio files

### ISSUE THREAD

**Issue by cagbal** [googlecreativelab/teachablemachine-community#35]
Hi, 

Is there any plan or way to upload our own dataset containing mp3 files? That would be perfect if we are able to upload pre-recorded audio files to the teachable machines. 

As far as I understand, currently the only way is to record the data through the teachable machine.

**Comment by hapticdata** [comment]
Hi, 
Yes, this is definitely a feature we would like to add. We don't know exactly when we will be able to release this feature, but it is high up on our list.

**Comment by irealva** [comment]
Thanks for your feature request idea. We're going to close this issue for now as we're not actively working on it just yet, but rest assured we've made a note of it.
