### ISSUE TITLE
Importing Keras Model with Python

### ISSUE THREAD

**Issue by ssaltwick** [googlecreativelab/teachablemachine-community#37]
I exported an image model using the Keras format (.h5 file), but cannot load it. In Python I'm doing the following.

`from keras.models import load_model
model = load_model('keras_model.h5')
`

But I get the following error
`TypeError: __init__() got an expected keyword argument 'ragged'`

Is this a problem with the export format or is there a different way to load it?

**Comment by ssaltwick** [comment]
Incompatible with the old version of Tensorflow I was using. Upgrading to newest worked.

**Comment by digvijay77** [comment]
still not working
