### ISSUE TITLE
Export Class + Download Samples to images + Pascal VOC XML?

### ISSUE THREAD

**Issue by gctommy** [googlecreativelab/teachablemachine-community#38]
I already have my own setup locally to generate training models. Would it be possible to use Teachable Machine not for the training function but just for the webcam/samples (especially the “Import images from Google Drive”) function to export images with the option to save the Class labels in Pascal VOC XML format?

**Comment by cwervo** [comment]
+1, this would be dope.

I imagine @gctommy you'd be able to do something like this if you remixed the `model-viewer` example at https://glitch.com/@teachablemachine/teachable-machine-starter-projects

**Comment by hapticdata** [comment]
Hello,
For now supporting this feature is beyond the scope of what we have planned.  Are you aware of the "download samples" features available on each class? There is also the "Download Project as File" feature in the top-left menu. This file is a .tm but its really a zip that you can rename and unzip to get your whole project including labels in json.

**Comment by irealva** [comment]
Thanks for your feature request idea. We're going to close this issue for now as we're not actively working on it just yet, but rest assured we've made a note of it.
