### ISSUE TITLE
Unexpected memory leak with the P5 snippet?

### ISSUE THREAD

**Issue by cwervo** [googlecreativelab/teachablemachine-community#39]
👋🏼

When I tried loading the model in P5.js it gave me this memory leak warning below. I know ML in the browser is still pretty taxing, so this may be expected usage, but is this load common?

![image](https://user-images.githubusercontent.com/5826638/68718352-f604a200-0576-11ea-9a7a-6aa80813c14f.png)

Note: I took the snippet from the TM code & inserted it into the P5 template. Is that not the recommended usage? You can [see the code & the project on editor.p5.js](https://editor.p5js.org/AndresCuervo/sketches/W7jI_BWNY)

**Comment by irealva** [comment]
@joeyklee or @shiffman would you like to look at this?

**Comment by joeyklee** [comment]
@irealva - Arg! Looks like we have a memory leak. I thought this was resolved in `0.4.2` but it seems something got passed me. I'll take a look. Thanks for flagging this!

**Comment by joeyklee** [comment]
@irealva - This should be resolved with https://github.com/ml5js/ml5-library/pull/697 - I will plan to do another ml5 release in the next day or so. Thank you!

**Comment by shiffman** [comment]
Thank you @joeyklee for looking at this!!!

**Comment by joeyklee** [comment]
@irealva - making a note that #46 should resolve the memory leak issue in the image classifier :)

**Comment by irealva** [comment]
Great, just merged that and thus closing this issue. Thanks all!

**Comment by joeyklee** [comment]
Thank you! 🙏

**Comment by AliKarpuzoglu** [comment]
The real issue here was actually that the flippedVideo was not removed after being drawn. 
`flippedVideo.remove()`  
should be called at the end of the classifyVideo() function. I created a pull request #78 for this
