### ISSUE TITLE
How to open .h5 file in Python?

### ISSUE THREAD

**Issue by shivapower1985** [googlecreativelab/teachablemachine-community#42]
I tried teachable machine image classification model. I has downloaded (.h5) model file of the image model I built using "Export Model>tensorflow>keras". I want to view the code in Pycharm IDE. How to open the (.h5) model in python. Please advice.

**Comment by GautamBose** [comment]
Checkout the snippet added in #44 for an overview on how to use the keras .h5 model in your python projects.
