### ISSUE TITLE
(TF:2.0)ValueError: could not broadcast input array from shape (224,224,4) into shape (224,224,3)

### ISSUE THREAD

**Issue by pwnmactep** [googlecreativelab/teachablemachine-community#54]
Hello , 
i try to run the example code and changed the line  `image = Image.open('test.jpg')` 

i get Error : 

`Traceback (most recent call last):
  File "test.py", line 28, in <module>
    data[0] = normalized_image_array
ValueError: could not broadcast input array from shape (224,224,4) into shape (224,224,3) 

What did i wrong ?

EDIT: Changed to bmp format fixed it..

**Comment by keyauto** [comment]
thank you very much!
I want to clarify png and bmp 256 don't work, only bmp 24 bit

**Comment by kalilinux-png** [comment]
@keyauto  and @pwnmactep  Have a look at this issue I think it will help you solve this issue 
[https://github.com/carpedm20/DCGAN-tensorflow/issues/162#issuecomment-899969767](url)

**Comment by pwnmactep** [comment]
Ty

shubham yadav ***@***.***> schrieb am So., 11. Sept. 2022,
13:35:

**Comment by pwnmactep** [comment]
TY bratan

Alexandr ***@***.***> schrieb am Sa., 21. Aug. 2021, 19:25:
