### ISSUE TITLE
Grouping multiple images as single class

### ISSUE THREAD

**Issue by gokhandilek** [googlecreativelab/teachablemachine-community#64]
I was just wondering if it would be possible to use multiple images as a single class. 
For example:
Image1,Image2, Image3 (Class 1)
Image4,Image5, Image6 (Class 1)

Image7,Image8, Image9 (Class 2)
Image9,Image10, Image11 (Class 2)

Thank you.

**Comment by irealva** [comment]
Hi @gokhandilek could you be a bit more explicit about the question? I'm not sure I follow. Do you mean when you're training in the Teachable Machine app? Or when you're running an inference using the API?

**Comment by gokhandilek** [comment]
Hello,
When you are training in the Teachable Machine app, you can only have single category image in a class.
I would like to place multiple category images in a single class.

For example.. I want to place cats, dogs and birds in the same class as animals.
I want to place kids and adults as humans in the same category. 
Would this be possible?
Or do you recommend to initially train each subcategory like cats. Then train it for animals?

**Comment by mstale007** [comment]
Hi, @gokhandilek I think that a better solution for this would be to keep the individual sub-category like cats, dogs or a bird in different classes while training and then while prediction you can programmatically add conditions such as if its a "dog", return "animal".That will give better accuracy as compared to keeping everything in one class called "animal". This will work if the number of unique sub-categories like dog, cat or rabbit is limited(not many) and known but if you want to generalize it for all possible animals then you should try a different approach.

**Comment by gokhandilek** [comment]
Thanks for clarifying that.
How about the kind of dogs? For example, Golden retrievers & chihuahuas etc..
Would I need a class per type of dog as well?
Do I need three seperate models which will predict that it is an animal, it is a dog & it is chihuahua?
And how would you chain these models if this is the case?

**Comment by irealva** [comment]
If you're specifically looking to classify dog breeds you might be better off just using mobilenet classes.

https://github.com/tensorflow/tfjs-models/tree/master/mobilenet

Checkout all the labels here: https://github.com/tensorflow/tfjs-models/blob/master/mobilenet/src/imagenet_classes.ts
