### ISSUE TITLE
How to join 2 trained model data?

### ISSUE THREAD

**Issue by PixsaOJ** [googlecreativelab/teachablemachine-community#67]
Hi! I was wondering, how can I join 2 trained model data together? e.g my friend wants me to help with training AI to recognize some objects. I know we could take and share photos but is there any other clever way? Maybe joining JSON data?

**Comment by irealva** [comment]
I @PixsaOJ you might be able to do this with the tensorflow sequential API that lets you link models together like this: https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/src/teachable-mobilenet.ts#L361

But to be honest this is not something we have tried.

**Comment by PixsaOJ** [comment]
> I @PixsaOJ you might be able to do this with the tensorflow sequential API that lets you link models together like this: https://github.com/googlecreativelab/teachablemachine-community/blob/master/libraries/image/src/teachable-mobilenet.ts#L361
> 
> But to be honest this is not something we have tried.

Thank you, I will try that when I get a time
