### ISSUE TITLE
Installing OpenCV Error

### ISSUE THREAD

**Issue by Wichtel02** [googlecreativelab/teachablemachine-community#71]
Everytime I try to install OpenCV with the given Command ` pip3 install Pillow opencv-python opencv-contrib-python
`
I get the Error:

> Collecting Pillow
    Using cached https://files.pythonhosted.org/packages/5b/bb/cdc8086db1f15d0664dd22a62c69613cdc00f1dd430b5b19df1bea83f2a3/Pillow-6.2.1.tar.gz
Collecting opencv-python
Could not find a version that satisfies the requirement opencv-python (from versions: )
No matching distribution found for opencv-python

I use the Google Coral Dev Board.

Hopefully somebody can tell me how I can fix this problem

**Comment by mqcmd196** [comment]
Please tell me your OS and OS version.

**Comment by Wichtel02** [comment]
Hi, Im using Mendel 4.0.0

**Comment by mqcmd196** [comment]
I think opencv-python for Mendel 4.0.0-pip3 is not distributed yet. If you want to install opencv-python, you have to build it yourself.

**Comment by Wichtel02** [comment]
Ok thank you, I thought I could install it like this because the command was given on the teachable machine website under Coral category. Thanks for your Help!

**Comment by Namburger** [comment]
You should be able to install it with apt:
```
sudo apt install python3-opencv
```
