### ISSUE TITLE
Data augmentation perfomed

### ISSUE THREAD

**Issue by connorladlyfredeen** [googlecreativelab/teachablemachine-community#74]
What sorts of image data augmentation are performed on the uploaded data set if any? I would like to perform some in advance but will not do so if it will be unnecessary effort.

**Comment by HalfdanJ** [comment]
Currently the only augmentation that is happening is shuffling the order of images (not even sure if that counts as augmentation?). But more augmentation is something we have talked about, so if you find specific techniques that work well for you, please don't hesitate updating this bug!

**Comment by connorladlyfredeen** [comment]
Awesome, thanks!
