### ISSUE TITLE
Teachable Machine Audio Model - .wav, .mp3 as input?

### ISSUE THREAD

**Issue by fabikm** [googlecreativelab/teachablemachine-community#77]
Dear,

First of all, I appreciate this project - amazing that someone can transform complex calculations into a simple tool like this. Good work.

**Is there a way how to import own sounds like .wav, or .mp3 format?**

Thank you,

Martin.

**Comment by colinhhamilton** [comment]
I'm trying to do this also.. Have you got a solution?

**Comment by fabikm** [comment]
Not yet, unfortunately.

**Comment by HalfdanJ** [comment]
Hi, thanks for this feature request. It's high on our list of things we want to get into the tool.

**Comment by micro-phonics** [comment]
that would be awesome and very powerful if you managed that!

**Comment by djovanoski** [comment]
Hello, as this comment is from Feb so are there news is this feature is planned and if yes   when can be expected.
Thanks,

**Comment by micro-phonics** [comment]
amazing ! that would be fantastic.

**Comment by irealva** [comment]
Thanks for your feature request idea. We're going to close this issue for now as we're not actively working on it just yet, but rest assured we've made a note of it.
