### ISSUE TITLE
Check if a probability stays above threshold for amount of time

### ISSUE THREAD

**Issue by Ic3m4n34** [googlecreativelab/teachablemachine-community#86]
I want to check if a probability stays above 0.8 for 5 seconds. How can I do this? Already asked my question here: https://stackoverflow.com/questions/60496144/javascript-check-if-condition-stays-true-for-5-seconds/60496467#60496467

But nothing seems to work

**Comment by irealva** [comment]
Hi @Ic3m4n34, just looking at the comments in the link you posted it seems like you solved this?

I see someone suggested using Date.now() which is what i was going to suggest

**Comment by Ic3m4n34** [comment]
Yepp. I ended up using this solution: https://stackoverflow.com/a/60496349
