### ISSUE TITLE
[ERROR] Input array from shape (224,224) into shape (224,224,3)

### ISSUE THREAD

**Issue by david-botelho-mariano** [googlecreativelab/teachablemachine-community#95]
I used google "teachablemachine" plataform (https://teachablemachine.withgoogle.com/train/image) to train image recognition of two image types "headphones" and "not headphones" . I used everything from official documentation like the python script to test predictions using keras (https://github.com/googlecreativelab/teachablemachine-community/blob/master/snippets/markdown/image/tensorflow/keras.md). Even so, I am getting the error above trying to predict the same image that I used to train the model:

`ValueError: could not broadcast input array from shape (224,224) into shape (224,224,3)`

Link to demonstrate the problem:
*https://colab.research.google.com/drive/1flGQ8n7WVK-aTYWipdiiYjdVl2hZCWj-
*the full dataset used is avaliable at the colab link.
*image size are 53x53.
*tested using tensorflow 1.x and tensorflow 2.x
*google chrome version: 80.0.3987.149 (Official Build) (64-bit).

**Comment by david-botelho-mariano** [comment]
First problem detected: inserting greyscale image cause it to be single channel you need to convert it to 3 channels.

Second problem detected: input image smaller than 224x244 dont use the function "Image.ANTIALIAS"


Example code fixing this problems:

```
import tensorflow.keras
from PIL import Image, ImageOps
import numpy as np


model = tensorflow.keras.models.load_model('keras_model.h5')
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

image = Image.open("2E.jpg").convert('RGB')
size = (224, 224)
image = ImageOps.fit(image, size)

image_array = np.asarray(image)
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
data[0] = normalized_image_array

prediction = model.predict(data)
print(prediction)
```

**Comment by sahal-mulki** [comment]
@david-botelho-mariano Thank you so much!
I am making this program to detect pnuemonia( https://github.com/sahal-mulki/coron-ai )

And your solution helped alot!

**Comment by david-botelho-mariano** [comment]
> @david-botelho-mariano Thank you so much!
> I am making this program to detect pnuemonia( https://github.com/sahal-mulki/coron-ai )
> 
> And your solution helped alot!

Glad to hear that, just to know, where do you live?

**Comment by sahal-mulki** [comment]
Sorry cant say
